// Copyright 2026 Küstenlogik
// SPDX-License-Identifier: Apache-2.0

using System.Text.Json;
using Kuestenlogik.Bowire.Protocol.Dis.Pdu;
using Kuestenlogik.Bowire.Protocol.Dis.Records;

namespace Kuestenlogik.Bowire.Protocol.Dis.Tests;

/// <summary>
/// The shipped sample recordings, checked against the plugin that has to
/// read them.
/// </summary>
/// <remarks>
/// <para>
/// The PDUs in <c>samples/</c> are generated bytes
/// (<c>scripts/generate-sample-recordings.py</c> patches the fields it
/// varies into a known-good template). Generated bytes that nothing
/// parses are a sample that looks fine in a diff and fails on first use,
/// so every step here goes through the real <see cref="EntityStatePdu"/>
/// unmarshaller and the real ECEF conversion.
/// </para>
/// <para>
/// The position assertions are the point of the multi-entity recording:
/// it exists so the map widget's per-entity track grouping has something
/// to group. A recording whose entities all sat on one spot, or whose
/// altitudes put a tank in the stratosphere, would exercise nothing.
/// </para>
/// </remarks>
public sealed class SampleRecordingTests
{
    private static string SamplesDirectory
    {
        get
        {
            // Walk up to the repository root: the test binary lives under
            // artifacts/, whose depth is not something to hard-code.
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "samples")))
                dir = dir.Parent;
            Assert.NotNull(dir);
            return Path.Combine(dir!.FullName, "samples");
        }
    }

    private static List<(string Id, byte[] Bytes)> LoadSteps(string fileName)
    {
        using var doc = JsonDocument.Parse(
            File.ReadAllText(Path.Combine(SamplesDirectory, fileName)));
        var steps = new List<(string, byte[])>();
        foreach (var step in doc.RootElement.GetProperty("steps").EnumerateArray())
        {
            steps.Add((
                step.GetProperty("id").GetString()!,
                Convert.FromBase64String(step.GetProperty("responseBinary").GetString()!)));
        }
        return steps;
    }

    [Theory]
    [InlineData("convoy.bowire-recording.json")]
    [InlineData("exercise.bowire-recording.json")]
    public void EveryStepUnmarshalsAsAnEntityStatePdu(string fileName)
    {
        var steps = LoadSteps(fileName);
        Assert.NotEmpty(steps);

        foreach (var (id, bytes) in steps)
        {
            Assert.True(bytes.Length >= EntityStatePdu.MinimumWireLength,
                $"{id}: {bytes.Length} bytes, below the 144-byte minimum");

            var pdu = EntityStatePdu.Unmarshal(bytes);
            Assert.False(string.IsNullOrWhiteSpace(pdu.Marking.Marking),
                $"{id}: no entity marking, so the map has nothing to group by");
        }
    }

    [Theory]
    [InlineData("convoy.bowire-recording.json")]
    [InlineData("exercise.bowire-recording.json")]
    public void EveryStepCarriesAPlottablePosition(string fileName)
    {
        foreach (var (id, bytes) in LoadSteps(fileName))
        {
            var fix = GeocentricCoordinate.ToWgs84(EntityStatePdu.Unmarshal(bytes).Location);

            Assert.True(fix.HasValue, $"{id}: location does not convert to a position");
            Assert.InRange(fix!.Value.Latitude, -90.0, 90.0);
            Assert.InRange(fix.Value.Longitude, -180.0, 180.0);
            // Northern Germany and the western Baltic — the scenario's
            // stated area. A conversion sign error lands outside it while
            // still producing a perfectly valid-looking coordinate.
            Assert.InRange(fix.Value.Latitude, 53.0, 55.0);
            Assert.InRange(fix.Value.Longitude, 9.0, 12.5);
        }
    }

    [Fact]
    public void TheExerciseSeparatesItsEntitiesInSpace()
    {
        var byMarking = new Dictionary<string, List<(double Lat, double Lon, double Alt)>>(
            StringComparer.Ordinal);

        foreach (var (_, bytes) in LoadSteps("exercise.bowire-recording.json"))
        {
            var pdu = EntityStatePdu.Unmarshal(bytes);
            var fix = GeocentricCoordinate.ToWgs84(pdu.Location)!.Value;
            var marking = pdu.Marking.Marking!.Trim();
            if (!byMarking.TryGetValue(marking, out var list))
                byMarking[marking] = list = [];
            list.Add(fix);
        }

        Assert.Equal(10, byMarking.Count);

        // Every entity moves. A track that never leaves its first
        // position draws no trajectory, so a recording of stationary
        // entities would silently test nothing.
        foreach (var (marking, points) in byMarking)
        {
            Assert.True(points.Count > 1, $"{marking}: a single PDU is not a track");
            var moved = points.Any(p =>
                Math.Abs(p.Lat - points[0].Lat) > 1e-4 ||
                Math.Abs(p.Lon - points[0].Lon) > 1e-4);
            Assert.True(moved, $"{marking}: never moves");
        }

        // The convoys drive on the ground and the drone flies. Altitude
        // is what separates them, and it is the field the old convoy
        // sample got wrong — a tank at 15.5 km.
        Assert.All(byMarking["ALPHA-1"], p => Assert.InRange(p.Alt, -50.0, 200.0));
        Assert.All(byMarking["KITE-07"], p => Assert.InRange(p.Alt, 1000.0, 1500.0));

        // Convoy members are spread along their road from the first
        // frame, not stacked on the leader until it pulls away.
        var alpha1 = byMarking["ALPHA-1"][0];
        var alpha3 = byMarking["ALPHA-3"][0];
        Assert.True(Math.Abs(alpha1.Lon - alpha3.Lon) > 1e-3,
            "the convoy starts nose-to-tail, not on one point");
    }

    [Fact]
    public void TheExerciseCarriesBothSidesOfTheEngagement()
    {
        var forces = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (_, bytes) in LoadSteps("exercise.bowire-recording.json"))
            forces.Add(EntityStatePdu.Unmarshal(bytes).Force.ToString());

        // Friendly and Opposing both present: the map colours by track,
        // but the affinity is what the tactical symbology reads.
        Assert.True(forces.Count >= 2, $"only one force present: {string.Join(", ", forces)}");
    }
}
